# Copyright (c) 2026 Axelspire Inc.
# at3am Windows install / refresh for 3AM vanity (module + digest) or community GitHub tag.
#
#   irm https://axel.<id>.3am.global/root/agent/at3am/install.ps1 | iex
#
# Bake marker @THREEAM_AGENT_BASE@ is rewritten at S3 publish time.
#Requires -Version 5.1
param(
  [string]$AgentBase = ""
)

$ErrorActionPreference = "Stop"
$REPO = if ($env:AT3AM_REPO) { $env:AT3AM_REPO } else { "Axelspire/at3am" }

function Get-PublishedAgentBase {
  return "@THREEAM_AGENT_BASE@"
}

function Resolve-AgentBase {
  param([string]$ArgBase)
  if ($env:THREEAM_AGENT_BASE) { return $env:THREEAM_AGENT_BASE.TrimEnd("/") }
  if ($ArgBase) { return $ArgBase.TrimEnd("/") }
  $pub = Get-PublishedAgentBase
  if ($pub -match "^https?://") { return $pub.TrimEnd("/") }
  return ""
}

function Test-ModuleValue {
  param([string]$Module)
  if ([string]::IsNullOrWhiteSpace($Module)) { throw "empty MODULE" }
  if ($Module -match '[\\/]' -or $Module -match '\.\.') { throw "invalid MODULE: $Module" }
  return $Module.Trim()
}

function Get-FileSha256Hex {
  param([string]$Path)
  return (Get-FileHash -Algorithm SHA256 -Path $Path).Hash.ToLowerInvariant()
}

function ConvertTo-ResponseText {
  param($Content)
  if ($null -eq $Content) { return "" }
  if ($Content -is [byte[]]) {
    return [System.Text.Encoding]::UTF8.GetString($Content)
  }
  return [string]$Content
}

function Get-UrlText {
  param([string]$Uri)
  $resp = Invoke-WebRequest -Uri $Uri -UseBasicParsing
  return (ConvertTo-ResponseText -Content $resp.Content).Trim()
}

function Get-Platform {
  $arch = if ([Environment]::Is64BitProcess) {
    if ($env:PROCESSOR_ARCHITECTURE -match "ARM") { "arm64" } else { "amd64" }
  } else { "arm64" }
  return "windows-$arch"
}

function Get-ConfigDir {
  if ($env:AT3AM_CONFIG_DIR) { return $env:AT3AM_CONFIG_DIR }
  return (Join-Path $env:USERPROFILE ".config\at3am")
}

function Get-LibDir {
  if ($env:AT3AM_LIB_DIR) { return $env:AT3AM_LIB_DIR }
  return (Join-Path $env:LOCALAPPDATA "3am\at3am")
}

function Get-BinDir {
  if ($env:AT3AM_BIN_DIR) { return $env:AT3AM_BIN_DIR }
  return (Join-Path $env:USERPROFILE ".local\bin")
}

function Write-AgentEnv {
  param([string]$Base, [string]$Module, [string]$Companion, [string]$Platform)
  $cfg = Get-ConfigDir
  New-Item -ItemType Directory -Force -Path $cfg | Out-Null
  @"
# Generated by at3am install — public defaults only, no secrets.
THREEAM_AGENT_BASE=$Base
AT3AM_MODULE=$Module
AT3AM_COMPANION=$Companion
AT3AM_PLATFORM=$Platform
"@ | Set-Content -Path (Join-Path $cfg "agent.env") -Encoding utf8
}

function Install-UpgradeWrapper {
  param([string]$LibDir, [string]$BinDir)
  New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
  $wrapper = @'
# at3am self-upgrade wrapper (vanity installs). Set AT3AM_NO_UPGRADE=1 to skip.
$ErrorActionPreference = "Stop"
$cfg = if ($env:AT3AM_CONFIG_DIR) { $env:AT3AM_CONFIG_DIR } else { Join-Path $env:USERPROFILE ".config\at3am" }
$lib = if ($env:AT3AM_LIB_DIR) { $env:AT3AM_LIB_DIR } else { Join-Path $env:LOCALAPPDATA "3am\at3am" }
$real = Join-Path $lib "at3am.exe"
$envFile = Join-Path $cfg "agent.env"
$base = $env:THREEAM_AGENT_BASE
$have = $env:AT3AM_MODULE
if (Test-Path $envFile) {
  Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*THREEAM_AGENT_BASE=(.*)$') { $base = $Matches[1].Trim() }
    if ($_ -match '^\s*AT3AM_MODULE=(.*)$') { $have = $Matches[1].Trim() }
  }
}
if ($base -and $env:AT3AM_NO_UPGRADE -ne "1") {
  try {
    $want = (Invoke-WebRequest -Uri "$base/MODULE" -UseBasicParsing).Content.ToString().Trim()
    if ($want -and $want -ne $have) {
      Write-Host "at3am: module $have → $want; self-upgrading…" -ForegroundColor Cyan
      $install = (Invoke-WebRequest -Uri "$base/install.ps1" -UseBasicParsing).Content
      Invoke-Expression $install
    }
  } catch {
    Write-Host "at3am: upgrade check skipped: $_" -ForegroundColor Yellow
  }
}
if (-not (Test-Path $real)) { throw "at3am binary missing at $real; re-run install" }
& $real @args
exit $LASTEXITCODE
'@
  Set-Content -Path (Join-Path $BinDir "at3am.ps1") -Value $wrapper -Encoding utf8
  # Convenience cmd shim
  @"
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0at3am.ps1" %*
"@ | Set-Content -Path (Join-Path $BinDir "at3am.cmd") -Encoding ascii
  $hook = Join-Path $LibDir "at3am-hook.exe"
  if (Test-Path $hook) {
    Copy-Item $hook (Join-Path $BinDir "at3am-hook.exe") -Force
  }
}

$base = Resolve-AgentBase -ArgBase $AgentBase
$platform = Get-Platform
$work = Join-Path $env:TEMP ("at3am-install-" + [guid]::NewGuid().ToString("n"))
New-Item -ItemType Directory -Path $work | Out-Null
$zipPath = Join-Path $work "$platform.zip"

try {
  if ($base) {
    Write-Host "agent base: $base"
    $module = Test-ModuleValue (Get-UrlText -Uri "$base/MODULE")
    Write-Host "module: $module"
    $expected = (Get-UrlText -Uri "$base/tags/$module/$platform").ToLowerInvariant()
    if (-not $expected) { throw "missing tags/$module/$platform" }

    $candidates = New-Object System.Collections.Generic.List[string]
    [void]$candidates.Add("$base/archive/$module/$platform.zip")
    try {
      $alt = (Get-UrlText -Uri "$base/archive/$module/$platform.url")
      if ($alt -match "^https?://") { [void]$candidates.Add($alt) }
    } catch { }
    [void]$candidates.Add("https://github.com/$REPO/releases/download/$module/$platform.zip")

    $fetched = $false
    foreach ($archiveUrl in $candidates) {
      Write-Host "fetching $archiveUrl"
      try {
        Invoke-WebRequest -Uri $archiveUrl -OutFile $zipPath -UseBasicParsing
        $actual = Get-FileSha256Hex -Path $zipPath
        if ($expected -ne $actual) {
          Write-Host "digest mismatch (got $actual); trying next"
          Remove-Item -Force $zipPath -ErrorAction SilentlyContinue
          continue
        }
        Write-Host "digest OK ($actual)"
        $fetched = $true
        break
      } catch {
        Write-Host "fetch failed: $_"
        Remove-Item -Force $zipPath -ErrorAction SilentlyContinue
      }
    }
    if (-not $fetched) { throw "could not fetch $platform.zip with digest $expected" }

    $companionVer = ""
    try { $companionVer = Get-UrlText -Uri "$base/companion/VERSION" } catch { }
  } else {
    if ([string]::IsNullOrWhiteSpace($env:AT3AM_MODULE)) {
      $rel = Invoke-RestMethod -Uri "https://api.github.com/repos/$REPO/releases/latest"
      $module = Test-ModuleValue $rel.tag_name
      Write-Host "community mode: resolving latest tag → $module"
    } else {
      $module = Test-ModuleValue $env:AT3AM_MODULE
    }
    Write-Host "GitHub mode: $REPO@$module ($platform)"
    $url = "https://github.com/$REPO/releases/download/$module/$platform.zip"
    Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing
    $companionVer = ""
  }

  $lib = Get-LibDir
  $bin = Get-BinDir
  New-Item -ItemType Directory -Force -Path $lib | Out-Null
  New-Item -ItemType Directory -Force -Path $bin | Out-Null
  $extract = Join-Path $work "extract"
  New-Item -ItemType Directory -Force -Path $extract | Out-Null
  Expand-Archive -Path $zipPath -DestinationPath $extract -Force

  Get-ChildItem $extract -Recurse -File | Where-Object {
    $_.Name -match '^at3am(\.exe)?$' -or $_.Name -match '^at3am-hook(\.exe)?$'
  } | ForEach-Object {
    Copy-Item $_.FullName (Join-Path $lib $_.Name) -Force
  }

  if ($base) {
    $compLib = Join-Path $lib "companion"
    New-Item -ItemType Directory -Force -Path $compLib | Out-Null
    foreach ($name in @("VERSION", "README.md", "agent.env.tmpl")) {
      try {
        Invoke-WebRequest -Uri "$base/companion/$name" -OutFile (Join-Path $compLib $name) -UseBasicParsing
      } catch { }
    }
    Write-AgentEnv -Base $base -Module $module -Companion $companionVer -Platform $platform
    Install-UpgradeWrapper -LibDir $lib -BinDir $bin
  } else {
    Get-ChildItem $lib -Filter "at3am*" -File | ForEach-Object {
      Copy-Item $_.FullName (Join-Path $bin $_.Name) -Force
    }
  }

  Write-Host "✅ at3am $module installed" -ForegroundColor Green
  Write-Host "   binary:  $(Join-Path $lib 'at3am.exe')"
  Write-Host "   PATH:    add $bin to User PATH if needed"
  if ($base) {
    Write-Host "   Upgrade: self-upgrades on every run against $base/MODULE"
  }
} finally {
  Remove-Item -Recurse -Force $work -ErrorAction SilentlyContinue
}
