#!/bin/sh
# Copyright (c) 2026 Axelspire Inc.
# at3am one-curl install / refresh for 3AM vanity (module + digest) or community GitHub tag.
#
# Vanity (baked at publish):
#   curl -fsSL https://axel.<id>.3am.global/root/agent/at3am/install.sh | sh
#
# Bake marker @THREEAM_AGENT_BASE@ is rewritten at S3 publish time.
set -e

REPO="${AT3AM_REPO:-Axelspire/at3am}"
GH_API="${GITHUB_API_URL:-https://api.github.com}"

threeam_die() { echo "ERROR: $*" >&2; exit 1; }
threeam_info() { echo "$*"; }

threeam_published_base() {
  # bake-marker: value replaced at S3 publish time
  printf '%s' '@THREEAM_AGENT_BASE@'
}

threeam_resolve_base() {
  _base="${THREEAM_AGENT_BASE:-}"
  if [ -z "${_base}" ] && [ -n "${1:-}" ]; then
    _base="$1"
  fi
  if [ -z "${_base}" ]; then
    _pub="$(threeam_published_base)"
    case "${_pub}" in
      https://*|http://*) _base="${_pub}" ;;
    esac
  fi
  printf '%s' "${_base}" | sed 's|/*$||'
}

threeam_sanitize_module() {
  _m="$(printf '%s' "$1" | tr -d '\r\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  [ -n "${_m}" ] || threeam_die "empty MODULE"
  case "${_m}" in
    */*|*..*|*" "*) threeam_die "invalid MODULE: ${_m}" ;;
  esac
  printf '%s' "${_m}"
}

threeam_platform() {
  OS=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$OS" in
    darwin*) OS="darwin" ;;
    linux*) OS="linux" ;;
    mingw*|msys*|cygwin*) OS="windows" ;;
    *) threeam_die "unsupported OS: $OS" ;;
  esac
  ARCH=$(uname -m)
  case "$ARCH" in
    x86_64|amd64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    armv7l|armv6l|arm) ARCH="arm" ;;
    i386|i686) ARCH="386" ;;
    *) threeam_die "unsupported architecture: $ARCH" ;;
  esac
  printf '%s' "${OS}-${ARCH}"
}

threeam_sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    threeam_die "need sha256sum or shasum"
  fi
}

threeam_fetch() {
  # $1=url $2=outfile
  curl -fsSL -o "$2" "$1"
}

threeam_fetch_text() {
  curl -fsSL "$1"
}

threeam_config_dir() {
  printf '%s' "${AT3AM_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/at3am}"
}

threeam_lib_dir() {
  printf '%s' "${AT3AM_LIB_DIR:-$HOME/.local/lib/3am/at3am}"
}

threeam_bin_dir() {
  printf '%s' "${AT3AM_BIN_DIR:-$HOME/.local/bin}"
}

threeam_write_env() {
  _cfg="$(threeam_config_dir)"
  mkdir -p "${_cfg}"
  cat >"${_cfg}/agent.env" <<EOF
# Generated by at3am install — public defaults only, no secrets.
THREEAM_AGENT_BASE=${1}
AT3AM_MODULE=${2}
AT3AM_COMPANION=${3:-}
AT3AM_PLATFORM=${4}
EOF
}

threeam_install_wrapper() {
  # PATH entry that self-upgrades on every run when AGENT_BASE is set.
  _bin="$(threeam_bin_dir)"
  _lib="$(threeam_lib_dir)"
  mkdir -p "${_bin}"
  cat >"${_bin}/at3am" <<'WRAP'
#!/bin/sh
set -e
CFG="${AT3AM_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/at3am}"
LIB="${AT3AM_LIB_DIR:-$HOME/.local/lib/3am/at3am}"
REAL="${LIB}/at3am"
if [ -f "${CFG}/agent.env" ]; then
  # shellcheck disable=SC1090
  . "${CFG}/agent.env"
fi
BASE="${THREEAM_AGENT_BASE:-}"
if [ -n "${BASE}" ] && [ "${AT3AM_NO_UPGRADE:-0}" != "1" ]; then
  WANT=$(curl -fsSL "${BASE}/MODULE" 2>/dev/null | tr -d '\r\n' || true)
  HAVE="${AT3AM_MODULE:-}"
  if [ -n "${WANT}" ] && [ "${WANT}" != "${HAVE}" ]; then
    echo "at3am: module ${HAVE:-none} → ${WANT}; self-upgrading…" >&2
    curl -fsSL "${BASE}/install.sh" | sh
    # shellcheck disable=SC1090
    . "${CFG}/agent.env"
  fi
fi
if [ ! -x "${REAL}" ]; then
  echo "at3am: binary missing at ${REAL}; re-run install" >&2
  exit 127
fi
exec "${REAL}" "$@"
WRAP
  chmod +x "${_bin}/at3am"
  # Hook binary: no upgrade wrapper (certbot calls it directly); keep beside real at3am.
  if [ -x "${_lib}/at3am-hook" ]; then
    ln -sf "${_lib}/at3am-hook" "${_bin}/at3am-hook"
  fi
}

# ── main ──────────────────────────────────────────────────────────────────────

BASE="$(threeam_resolve_base "${1:-}")"
PLATFORM="$(threeam_platform)"
WORK="${TMPDIR:-/tmp}/at3am-install-$$"
mkdir -p "${WORK}"
trap 'rm -rf "${WORK}"' EXIT

if [ -n "${BASE}" ]; then
  threeam_info "agent base: ${BASE}"
  MODULE="$(threeam_sanitize_module "$(threeam_fetch_text "${BASE}/MODULE")")"
  threeam_info "module: ${MODULE}"
  EXPECTED="$(threeam_fetch_text "${BASE}/tags/${MODULE}/${PLATFORM}" | tr -d '\r\n' | tr 'A-F' 'a-f')"
  [ -n "${EXPECTED}" ] || threeam_die "missing tags/${MODULE}/${PLATFORM}"

  ZIP="${WORK}/${PLATFORM}.zip"
  ALT_URL=""
  if ALT_URL="$(threeam_fetch_text "${BASE}/archive/${MODULE}/${PLATFORM}.url" 2>/dev/null)"; then
    ALT_URL="$(printf '%s' "${ALT_URL}" | tr -d '\r\n')"
  else
    ALT_URL=""
  fi
  FETCHED=0
  for URL in \
    "${BASE}/archive/${MODULE}/${PLATFORM}.zip" \
    "${ALT_URL}" \
    "https://github.com/${REPO}/releases/download/${MODULE}/${PLATFORM}.zip"
  do
    case "${URL}" in
      https://*|http://*) ;;
      *) continue ;;
    esac
    threeam_info "fetching ${URL}"
    if threeam_fetch "${URL}" "${ZIP}"; then
      ACTUAL="$(threeam_sha256_file "${ZIP}")"
      if [ "${ACTUAL}" = "${EXPECTED}" ]; then
        threeam_info "digest OK (${ACTUAL})"
        FETCHED=1
        break
      fi
      threeam_info "digest mismatch (got ${ACTUAL}); trying next"
      rm -f "${ZIP}"
    else
      threeam_info "fetch failed; trying next"
      rm -f "${ZIP}"
    fi
  done
  [ "${FETCHED}" = "1" ] || threeam_die "could not fetch ${PLATFORM}.zip with digest ${EXPECTED}"

  COMPANION_VER=""
  if threeam_fetch "${BASE}/companion/VERSION" "${WORK}/COMPANION_VERSION" 2>/dev/null; then
    COMPANION_VER="$(tr -d '\r\n' <"${WORK}/COMPANION_VERSION")"
  fi
else
  # Community / OSS: prefer AT3AM_MODULE. Unset → GitHub latest tag (not for 3AM vanity).
  if [ -z "${AT3AM_MODULE:-}" ]; then
    MODULE="$(threeam_sanitize_module "$(curl -fsSL "${GH_API}/repos/${REPO}/releases/latest" \
      | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)")"
    threeam_info "community mode: resolving latest tag → ${MODULE}"
  else
    MODULE="$(threeam_sanitize_module "${AT3AM_MODULE}")"
  fi
  threeam_info "GitHub mode: ${REPO}@${MODULE} (${PLATFORM})"
  ZIP="${WORK}/${PLATFORM}.zip"
  threeam_fetch "https://github.com/${REPO}/releases/download/${MODULE}/${PLATFORM}.zip" "${ZIP}" \
    || threeam_die "download failed for ${MODULE}/${PLATFORM}.zip"
  # Optional digest from GitHub release asset metadata when jq/gh available — best-effort.
  EXPECTED=""
  if command -v gh >/dev/null 2>&1; then
    EXPECTED="$(gh api "repos/${REPO}/releases/tags/${MODULE}" \
      --jq ".assets[] | select(.name==\"${PLATFORM}.zip\") | .digest" 2>/dev/null \
      | sed 's/^sha256://' || true)"
  fi
  if [ -n "${EXPECTED}" ]; then
    ACTUAL="$(threeam_sha256_file "${ZIP}")"
    [ "${ACTUAL}" = "${EXPECTED}" ] || threeam_die "digest mismatch: expected ${EXPECTED} got ${ACTUAL}"
    threeam_info "digest OK (${ACTUAL})"
  else
    threeam_info "warning: no digest available in community mode (set THREEAM_AGENT_BASE for gated install)"
  fi
fi

LIB="$(threeam_lib_dir)"
BIN="$(threeam_bin_dir)"
mkdir -p "${LIB}" "${BIN}"
EXTRACT="${WORK}/extract"
mkdir -p "${EXTRACT}"
unzip -o "${ZIP}" -d "${EXTRACT}" >/dev/null

# Flatten platform subdirectory if present
find "${EXTRACT}" -maxdepth 3 \( -name 'at3am' -o -name 'at3am.exe' -o -name 'at3am-hook' -o -name 'at3am-hook.exe' \) -type f | while read -r f; do
  mv -f "$f" "${LIB}/$(basename "$f")"
done
chmod +x "${LIB}/at3am" "${LIB}/at3am-hook" 2>/dev/null || true

if [ -n "${BASE}" ]; then
  # Companion (server-side) — VERSION + env template + any extra files
  COMP_DIR="${WORK}/companion"
  mkdir -p "${COMP_DIR}"
  if threeam_fetch "${BASE}/companion/VERSION" "${COMP_DIR}/VERSION" 2>/dev/null; then
    mkdir -p "${LIB}/companion"
    cp -f "${COMP_DIR}/VERSION" "${LIB}/companion/VERSION"
    for name in README.md agent.env.tmpl; do
      if threeam_fetch "${BASE}/companion/${name}" "${COMP_DIR}/${name}" 2>/dev/null; then
        cp -f "${COMP_DIR}/${name}" "${LIB}/companion/${name}"
      fi
    done
  fi
  threeam_write_env "${BASE}" "${MODULE}" "${COMPANION_VER}" "${PLATFORM}"
  threeam_install_wrapper
else
  # Community: install binaries directly on PATH (no wrapper / no latest)
  cp -f "${LIB}/at3am" "${BIN}/at3am" 2>/dev/null || true
  cp -f "${LIB}/at3am-hook" "${BIN}/at3am-hook" 2>/dev/null || true
  chmod +x "${BIN}/at3am" "${BIN}/at3am-hook" 2>/dev/null || true
fi

threeam_info "✅ at3am ${MODULE} installed"
threeam_info "   binary:  ${LIB}/at3am"
threeam_info "   PATH:    ${BIN}/at3am"
threeam_info "   Run:     at3am --help"
if [ -n "${BASE}" ]; then
  threeam_info "   Upgrade: self-upgrades on every run against ${BASE}/MODULE"
fi
